repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: requirements-txt-fixer
    files: ^(requirements.*\.txt)$
  - id: end-of-file-fixer
    exclude: ^.*/VERSION$
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: [--remove]
  - id: name-tests-test
    files: ^tests/.*\.py$
    args: [--django]
  - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
  - id: remove-tabs
    exclude: ^docs/(make.bat|Makefile)
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: [-w]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus, --keep-runtime-typing]
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: python3 -m flake8 .
    language: system
    types: [python]
    pass_filenames: false
  - id: mypy
    name: mypy
    entry: python3 -m mypy --config-file setup.cfg evacuator
    language: system
    types: [python]
    pass_filenames: false

ci:
  skip:
  - flake8  # checked with Github Actions
  - mypy  # checked with Github Actions
